from ..subtypable import SBool
from collections.abc import Hashable
from typing import Final, TypeVar

__all__ = ['TF_Bool', 'T_Bool', 'F_Bool', 'ALWAYS', 'NEVER_EVER']

I = TypeVar('I', bound=int)

class TF_Bool(SBool):
    def __new__(cls, witness: object, flavor: Hashable = ...) -> TF_Bool: ...
    def __invert__(self) -> TF_Bool: ...
    def __and__(self, other: I) -> TF_Bool: ...
    def __rand__(self, other: I) -> TF_Bool: ...
    def __or__(self, other: I) -> TF_Bool: ...
    def __xor__(self, other: I) -> TF_Bool: ...

class T_Bool(SBool):
    def __new__(cls, ignored: bool = True) -> T_Bool: ...
    def __invert__(self) -> SBool: ...

class F_Bool(SBool):
    def __new__(cls, ignored: bool = False) -> F_Bool: ...
    def __invert__(self) -> SBool: ...

ALWAYS: Final[T_Bool]
NEVER_EVER: Final[F_Bool]
