from .subtypable import SBool
from collections.abc import Hashable
from typing import Self

__all__ = ['FBool', 'truthy', 'falsy']

class FBool(SBool):
    def __new__(cls, witness: object, flavor: Hashable) -> Self: ...
    def __init__(self, witness: object, flavor: Hashable) -> None: ...
    def __and__(self, other: int) -> int: ...
    def __or__(self, other: int) -> int: ...
    def __xor__(self, other: int) -> int: ...
    def flavor(self) -> Hashable: ...

def truthy(flavor: Hashable) -> FBool: ...
def falsy(flavor: Hashable) -> FBool: ...
