from collections.abc import Hashable
from pythonic_fp.gadgets.sentinels.novalue import NoValue
from typing import Final, Self, overload

__all__ = ['SBool', 'TRUTH', 'LIE']

class SBool(int):
    @overload
    def __new__(cls, witness: object) -> Self: ...
    @overload
    def __new__(cls, witness: object, flavor: Hashable | NoValue = ...) -> Self: ...
    @overload
    def __init__(self, witness: object) -> None: ...
    @overload
    def __init__(self, witness: object, flavor: Hashable) -> None: ...
    def __invert__(self) -> int: ...
    def __and__(self, other: int) -> int: ...
    def __or__(self, other: int) -> int: ...
    def __xor__(self, other: int) -> int: ...

TRUTH: Final[SBool]
LIE: Final[SBool]
