from .subtypable import SBool
from collections.abc import Hashable
from pythonic_fp.gadgets.sentinels.novalue import NoValue
from typing import Final, Self

__all__ = ['TF_Bool', 'T_Bool', 'F_Bool', 'ALWAYS', 'NEVER']

class TF_Bool(SBool):
    def __new__(cls, witness: object, flavor: Hashable = ...) -> Self: ...
    def __invert__(self) -> TF_Bool: ...

class T_Bool(TF_Bool):
    def __new__(cls, witness: object = ..., flavor: Hashable | NoValue = ...) -> Self: ...
    def __and__(self, other: int) -> int: ...
    def __or__(self, other: int) -> int: ...
    def __xor__(self, other: int) -> int: ...

class F_Bool(TF_Bool):
    def __new__(cls, witness: object = ..., flavor: Hashable | NoValue = ...) -> Self: ...
    def __and__(self, other: int) -> int: ...
    def __or__(self, other: int) -> int: ...
    def __xor__(self, other: int) -> int: ...

ALWAYS: Final[TF_Bool]
NEVER: Final[TF_Bool]
